export const SET_MODE = 'SET_MODE'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_PLAYING = 'SET_PLAYING'

export const SET_SEQUENCELIST = 'SET_SEQUENCELIST'

export const SET_RANDOMLIST = 'SET_RANDOMLIST'

export const SET_CURRENTLIST = 'SET_CURRENTLIST'

export const SET_CURRENTSONG = 'SET_CURRENTSONG'

export const SET_CURRENTINDEX = 'SET_CURRENTINDEX'

export const SET_PLAYHISTORY = 'SET_PLAYHISTORY'

export const SET_FAVORITELIST = 'SET_FAVORITELIST'

export const SET_SEARCHHISTORY = 'SET_SEARCHHISTORY'

export const DEL_CURRENTLIST_ONE = 'DEL_CURRENTLIST_ONE'
